# Generated by Django 2.1.2 on 2018-12-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='number')),
                ('title', models.CharField(help_text='i.e. Finals Day', max_length=100, verbose_name='title')),
                ('date', models.DateField(verbose_name='date')),
                ('release', models.BooleanField(default=False, verbose_name='release the itenirary of the day')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='time')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Optional.', verbose_name='description')),
                ('venue_name', models.CharField(max_length=100, verbose_name='venue name')),
                ('venue_address', models.CharField(max_length=200, verbose_name='venue address')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itenirary.Day')),
            ],
        ),
    ]
