# Generated by Django 2.1.2 on 2018-12-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itenirary', '0002_auto_20181227_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='When the event ends.', verbose_name='end time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(help_text='When the event starts.', verbose_name='start time'),
        ),
    ]
