# Generated by Django 2.1.2 on 2019-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itenirary', '0004_auto_20181227_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='dsffdsd', max_length=8),
            preserve_default=False,
        ),
    ]
