# Generated by Django 2.1.2 on 2019-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itenirary', '0006_auto_20190105_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='number',
            field=models.SmallIntegerField(unique=True, verbose_name='number'),
        ),
    ]
