# Generated by Django 2.1.2 on 2018-12-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_auto_20181218_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='asc_round_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rounds.AcceptedRoundFile', verbose_name='Round file'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='asc_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Team', verbose_name='Team'),
        ),
    ]
