# Generated by Django 2.1.2 on 2018-12-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0003_auto_20181225_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='asc_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rounds.Round', verbose_name='Round'),
        ),
    ]
