# Generated by Django 2.1.2 on 2018-12-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0004_submission_asc_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='survey_link',
            field=models.URLField(blank=True, help_text='Optional. Add a link to a survey to be shown when visible but not active (to delegates).', verbose_name='survey link'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='asc_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rounds.Round', verbose_name='round'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='asc_round_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rounds.AcceptedRoundFile', verbose_name='round file'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='asc_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Team', verbose_name='team'),
        ),
    ]
