# Generated by Django 2.1.2 on 2018-12-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0006_auto_20181228_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='rough_notes',
            field=models.TextField(blank=True, help_text="Add any rough notes here. Will NOT be counted in the team's score.", verbose_name='rough notes'),
        ),
    ]
