# Generated by Django 2.1.2 on 2019-01-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181230_1357'),
        ('rounds', '0007_auto_20181228_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeAssessments',
            fields=[
            ],
            options={
                'verbose_name': 'Assessments -> Judges',
                'verbose_name_plural': 'Assessments -> Judges',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.judge',),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='round',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rounds.Round', verbose_name='round'),
        ),
    ]
