# Generated by Django 2.1.2 on 2019-01-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0008_auto_20190102_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='submitted',
            field=models.BooleanField(default=False, help_text='Whether or not the assessment has been submitted by judge.', verbose_name='submitted'),
        ),
    ]
