# Generated by Django 2.1.2 on 2019-01-03 17:43

from django.db import migrations, models
import django.db.models.deletion
import rounds.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181230_1357'),
        ('rounds', '0010_auto_20190103_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload a video in H.264/MPEG-4 AVC.', upload_to=rounds.helpers.video_upload_to, verbose_name='video')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional. Thumbnail of the video.', upload_to=rounds.helpers.video_thumbnail_upload_to, verbose_name='thumbnail')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rounds.Round', verbose_name='round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AlterField(
            model_name='assessment',
            name='rough_notes',
            field=models.TextField(blank=True, help_text="Optional. Will NOT be counted in the team's score.", verbose_name='rough notes'),
        ),
        migrations.AlterField(
            model_name='assessmentmark',
            name='rubric_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rounds.RubricMark'),
        ),
    ]
