# Generated by Django 2.1.2 on 2019-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0011_auto_20190103_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='slug',
            field=models.SlugField(default='dffdds', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubric',
            name='release',
            field=models.BooleanField(default=False, help_text='If this is True, then the round is visible to judge.', verbose_name='release rubric'),
        ),
    ]
