# Generated by Django 2.1.2 on 2019-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0012_auto_20190105_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='slug',
            field=models.SlugField(max_length=8, null=True),
        ),
    ]
