# Generated by Django 2.1.2 on 2019-01-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0013_auto_20190105_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationvideo',
            name='slug',
            field=models.SlugField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='presentationvideo',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='rounds.Round', verbose_name='round'),
        ),
        migrations.AlterField(
            model_name='presentationvideo',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.Team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='asc_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='rounds.Round', verbose_name='round'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='asc_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='users.Team', verbose_name='team'),
        ),
    ]
