# Generated by Django 2.1.2 on 2018-12-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, help_text='Will not be shown.', max_length=100, verbose_name='description'),
        ),
    ]
