# Generated by Django 2.1.2 on 2018-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20181225_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='show_judges',
            field=models.BooleanField(default=True, help_text='Recommended. Displays in a section about the LIVE team.', verbose_name='viewable to judges'),
        ),
    ]
