# Generated by Django 2.1.2 on 2019-01-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_show_judges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['position_title'], 'verbose_name': 'LIVE Executive', 'verbose_name_plural': 'LIVE Executives'},
        ),
    ]
