# Generated by Django 2.1.2 on 2018-12-22 19:48

from django.db import migrations, models
import users.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, upload_to=users.helpers.profile_picture_upload_to, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='program',
            field=models.CharField(blank=True, max_length=150, verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=users.helpers.resume_upload_to, verbose_name='resume'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='school',
            field=models.CharField(blank=True, choices=[('University of Toronto St. George', 'University of Toronto St. George'), ('University of Toronto Scarborough', 'University of Toronto Scarborough'), ('University of Toronto Mississauga', 'University of Toronto Mississauga'), ('Ryerson University', 'Ryerson University'), ('York University', 'York University'), ('University of Western Ontario', 'University of Western Ontario'), ("Queen's University", "Queen's University"), ('Wilfrid Laurier University', 'Wilfrid Laurier University'), ('University of Waterloo', 'University of Waterloo'), ('McMaster University', 'McMaster University'), ('Brock University', 'Brock University'), ('University of Ottawa', 'University of Ottawa'), ('McGill University', 'McGill University'), ('University of British Columbia', 'University of British Columbia'), ('University of Guelph', 'University of Guelph'), ('Carleton University', 'Carleton University'), ('University of Ontario Institute of Technology', 'University of Ontario Institute of Technology'), ('Trent University', 'Trent University'), ('Acadia University', 'Acadia University'), ('University of Alberta', 'University of Alberta'), ('Algoma University', 'Algoma University'), ('Athabasca University', 'Athabasca University'), ("Bishop's University", "Bishop's University"), ('Brandon University', 'Brandon University'), ('University of Calgary', 'University of Calgary'), ('Cape Breton University', 'Cape Breton University'), ('Capilano University', 'Capilano University'), ('Concordia University', 'Concordia University'), ('Dalhousie University', 'Dalhousie University'), ('Dominican University College', 'Dominican University College'), ('École de technologie supérieure', 'École de technologie supérieure'), ("École nationale d'administration publique", "École nationale d'administration publique"), ('École Polytechnique de Montréal', 'École Polytechnique de Montréal'), ('Emily Carr University of Art and Design', 'Emily Carr University of Art and Design'), ('First Nations University of Canada', 'First Nations University of Canada'), ('University of the Fraser Valley', 'University of the Fraser Valley'), ('HEC Montréal', 'HEC Montréal'), ('Huron University College', 'Huron University College'), ('Institut national de la recherche scientifique', 'Institut national de la recherche scientifique'), ("University of King's College", "University of King's College"), ('Kwantlen Polytechnic University', 'Kwantlen Polytechnic University'), ('Lakehead University', 'Lakehead University'), ('Laurentian University', 'Laurentian University'), ('University of Lethbridge', 'University of Lethbridge'), ('MacEwan University', 'MacEwan University'), ('University of Manitoba', 'University of Manitoba'), ('Memorial University of Newfoundland', 'Memorial University of Newfoundland'), ('Mount Allison University', 'Mount Allison University'), ('Mount Royal University', 'Mount Royal University'), ('Mount Saint Vincent University', 'Mount Saint Vincent University'), ('Nipissing University', 'Nipissing University'), ('University of Northern British Columbia', 'University of Northern British Columbia'), ('NSCAD University', 'NSCAD University'), ('OCAD University', 'OCAD University'), ('Royal Military College of Canada', 'Royal Military College of Canada'), ('Royal Roads University', 'Royal Roads University'), ('Saint Francis Xavier University', 'Saint Francis Xavier University'), ("Saint Mary's University", "Saint Mary's University"), ('Saint Paul University', 'Saint Paul University'), ('Université Sainte-Anne', 'Université Sainte-Anne'), ('Simon Fraser University', 'Simon Fraser University'), ('St. Thomas University', 'St. Thomas University'), ('Thompson Rivers University', 'Thompson Rivers University'), ('University College of the North', 'University College of the North'), ('University of New Brunswick', 'University of New Brunswick'), ('University of Prince Edward Island', 'University of Prince Edward Island'), ('University of Regina', 'University of Regina'), ('University of Saskatchewan', 'University of Saskatchewan'), ('Université de Moncton', 'Université de Moncton'), ('Université de Montréal', 'Université de Montréal'), ('Université de Sherbrooke', 'Université de Sherbrooke'), ('Université du Québec en Abitibi-Témiscamingue', 'Université du Québec en Abitibi-Témiscamingue'), ('Université du Québec en Outaouais', 'Université du Québec en Outaouais'), ('Université du Québec à Chicoutimi', 'Université du Québec à Chicoutimi'), ('Université du Québec à Montréal', 'Université du Québec à Montréal'), ('Université du Québec à Rimouski', 'Université du Québec à Rimouski'), ('Université du Québec à Trois-Rivières', 'Université du Québec à Trois-Rivières'), ('Université Laval', 'Université Laval'), ('Vancouver Island University', 'Vancouver Island University'), ('University of Victoria', 'University of Victoria'), ('University of Windsor', 'University of Windsor'), ('University of Winnipeg', 'University of Winnipeg'), ('Université de Saint-Boniface', 'Université de Saint-Boniface')], help_text='If the school is not listed, please contact the admin', max_length=150, verbose_name='currently attending'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='seeking_status',
            field=models.CharField(blank=True, choices=[('Co-op', 'Seeking for co-op'), ('Internship', 'Seeking for an internship'), ('Post-graduation', 'Seeking for post-graduation'), ('Not seeking', 'Not seeking')], max_length=80, verbose_name='seeking status'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('First Year Undergraduate', 'First year undergraduate'), ('Second Year Undergraduate', 'Second year undergraduate'), ('Third Year Undergraduate', 'Third year undergraduate'), ('Fourth Year Undergraduate', 'Fourth year undergraduate'), ('Fifth Year Undergraduate', 'Fifth year undergraduate'), ('Sixth Year Undergraduate', 'Sixth year undergraduate')], max_length=40, verbose_name='year in school'),
        ),
    ]
