# Generated by Django 2.1.2 on 2018-12-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181221_2214'),
        ('users', '0002_auto_20181222_1948'),
    ]

    operations = [
    ]
