# Generated by Django 2.1.2 on 2018-12-28 15:52

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181227_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
