# Generated by Django 2.1.2 on 2018-12-30 13:57

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_judge_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherUser',
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'executive user',
                'verbose_name_plural': 'executive users',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='judge',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(help_text='Will be displayed to the partner.', max_length=130, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_package',
            field=models.CharField(choices=[('Title', 'Title'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Final day', 'Final day'), ('Associate', 'Associate'), ('Prize', 'Prize'), ('Custom', 'Custom')], help_text='Will be displayed to the partner.', max_length=60, verbose_name='package'),
        ),
    ]
