# Generated by Django 2.1.2 on 2019-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181230_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='profile_picture_block',
            field=models.BooleanField(blank=True, default=False, verbose_name='block profile picture'),
        ),
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The team's place in the competition.", null=True, verbose_name='place'),
        ),
    ]
