# Generated by Django 2.1.2 on 2019-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190103_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='profile_picture_block',
            field=models.BooleanField(blank=True, default=False, help_text="Only block the user's profile picture for partners.", verbose_name='block profile picture'),
        ),
    ]
