# Generated by Django 2.1.2 on 2019-01-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190105_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegates', to='users.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The team's place (ranking) in the competition.", null=True, verbose_name='ranking'),
        ),
    ]
