# Generated by Django 2.1.2 on 2018-11-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('logo', models.ImageField(blank=True, help_text='<strong>It is highly recommended that a logo should be uploaded if they are a partner.</strong>', null=True, upload_to='', verbose_name='logo')),
                ('partner', models.BooleanField(default=False, help_text='If true, this organization will be viewable to delegates.', verbose_name='is a partner')),
                ('partner_type', models.CharField(blank=True, help_text='Leave blank if organization is not a partner. This is viewable to delegates if organization is a partner. <br/>i.e. Title Partner', max_length=50, verbose_name='partner type')),
            ],
            options={
                'verbose_name': 'corporate organization',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('profile_picture', models.ImageField(blank=True, help_text='Please upload a 50x50 square ratio image.', null=True, upload_to='', verbose_name='picture')),
                ('biography', models.TextField(blank=True, help_text='Recommended to keep it short', verbose_name='biography')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate.CorporateOrganization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('profile_picture', models.ImageField(blank=True, help_text='Please upload a 50x50 square ratio image.', null=True, upload_to='', verbose_name='picture')),
                ('biography', models.TextField(blank=True, help_text='Recommended to keep it short', verbose_name='biography')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate.CorporateOrganization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Networker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('profile_picture', models.ImageField(blank=True, help_text='Please upload a 50x50 square ratio image.', null=True, upload_to='', verbose_name='picture')),
                ('biography', models.TextField(blank=True, help_text='Recommended to keep it short', verbose_name='biography')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate.CorporateOrganization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('profile_picture', models.ImageField(blank=True, help_text='Please upload a 50x50 square ratio image.', null=True, upload_to='', verbose_name='picture')),
                ('biography', models.TextField(blank=True, help_text='Recommended to keep it short', verbose_name='biography')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate.CorporateOrganization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
