# Generated by Django 2.1.2 on 2018-11-15 05:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUser',
            fields=[
            ],
            options={
                'verbose_name': 'other user',
                'verbose_name_plural': 'other users',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='delegate',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
