# Generated by Django 2.1.2 on 2018-11-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agreed_terms',
            field=models.DateTimeField(blank=True, null=True, verbose_name='agreed to all terms on'),
        ),
    ]
