# Generated by Django 2.1.2 on 2018-12-04 20:38

from django.db import migrations, models
import django.db.models.deletion
import rounds.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedRoundFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_accepted', models.SmallIntegerField(choices=[(0, 'Powerpoint (.pptx, .pptm, .ppt, .pdf)'), (1, 'Excel (.xlsx, .xlsm, .xls, .csv)'), (2, 'PDF (.pdf)'), (3, 'Word (.docx, .doc)'), (4, 'PDF/Word (.pdf, .docx, .doc)'), (5, 'Text (.txt)'), (6, 'Image (.png, .jpg, .jpeg, .gif)')], verbose_name='file type(s) accepted')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('show_title', models.BooleanField(default=True, verbose_name='show title')),
            ],
            options={
                'verbose_name': 'acceptable file for round',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Submissions for rounds allowed. Set True during round.', verbose_name='active')),
                ('visible', models.BooleanField(default=False, help_text='Round is visible. Set True during and after round.', verbose_name='visible')),
                ('number', models.SmallIntegerField(help_text='Ensure sure there is no other round with thesame number.', verbose_name='round number')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Optional. Write a publicly displayed description, that provides more details into the current round.', verbose_name='description')),
                ('details_file', models.FileField(blank=True, help_text='Optional. Upload a publicly displayed file, that provides more details into the current round.', upload_to='rounds/round/details/', verbose_name='file with details')),
                ('expected_deadline', models.DateTimeField(help_text='Please note: the web application will not automatically close the round, it needs to be done manually.', verbose_name='expected deadline')),
                ('show_deadline', models.BooleanField(default=False, help_text='If True, then the deadline will be shared publicly.', verbose_name='show deadline publicly')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.IntegerField(verbose_name='submitted by (id of user)')),
                ('submitted_file', models.FileField(upload_to=rounds.helpers.submission_upload_to, verbose_name='submitted file')),
                ('submitted_at', models.DateTimeField(verbose_name='date and time of submission')),
                ('latest', models.BooleanField(verbose_name='latest file')),
                ('asc_round_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rounds.AcceptedRoundFile')),
            ],
        ),
    ]
