# Generated by Django 2.1.2 on 2018-12-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_auto_20181223_1259'),
        ('corporate', '0004_auto_20181222_1347'),
    ]

    operations = [
    ]
