# Generated by Django 2.1.2 on 2018-11-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['position_title']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(help_text='i.e. Responsible for overseeing all logistical operations on the day of. To be seen by both delegates and partners.', max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position_title',
            field=models.IntegerField(choices=[(1, 'President'), (2, 'VP of Corporate Relations'), (3, 'Corporate Relations Manager'), (4, 'VP of Operations'), (5, 'Delegate Experience Manager'), (6, 'VP of Curriculum'), (7, 'Curriculum Manager'), (8, 'VP of Business Intelligence'), (9, 'Business Analyst'), (10, 'VP of Marketing'), (11, 'Marketing Manager'), (12, 'External Relations Manager'), (13, 'IT Solutions Manager'), (14, 'Board Member')], verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(help_text='Please upload a 500x500 square ratio image.', upload_to='', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='resume',
            field=models.FileField(help_text='visible only to partners', upload_to='', verbose_name='resume'),
        ),
    ]
