# Generated by Django 2.1.2 on 2018-11-14 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Display an image in the widget. Note it will be expanded to meet the widget's dimensions.", upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'portal image widget',
            },
        ),
        migrations.CreateModel(
            name='PortalWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('show_delegate', models.BooleanField(default=False)),
                ('show_partner', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False, help_text='Pin this at the top of the portal. Can only have this once.')),
            ],
            options={
                'verbose_name': 'portal widget',
            },
        ),
        migrations.CreateModel(
            name='TextNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Display a piece of text in the widget.', verbose_name='message')),
                ('send', models.BooleanField(default=False, help_text='If True, message will be sent after submitting this form.', verbose_name='send now')),
                ('sent', models.BooleanField(default=False, help_text='If True, message has been sent.', verbose_name='sent')),
            ],
        ),
        migrations.CreateModel(
            name='TextWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Display a piece of text in the widget.', verbose_name='text')),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_widget', to='notifications.PortalWidget')),
            ],
            options={
                'verbose_name': 'portal text widget',
            },
        ),
        migrations.AddField(
            model_name='imagewidget',
            name='widget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_widget', to='notifications.PortalWidget'),
        ),
    ]
