# Generated by Django 2.1.2 on 2018-11-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWidgetProxy',
            fields=[
            ],
            options={
                'verbose_name': 'image widget',
                'proxy': True,
                'indexes': [],
            },
            bases=('notifications.portalwidget',),
        ),
        migrations.CreateModel(
            name='TextWidgetProxy',
            fields=[
            ],
            options={
                'verbose_name': 'text widget',
                'proxy': True,
                'indexes': [],
            },
            bases=('notifications.portalwidget',),
        ),
        migrations.AlterField(
            model_name='imagewidget',
            name='image',
            field=models.ImageField(help_text="Display an image in the widget.<br/><strong>Recommended that you have an image with large dimensions so it can be stretched based off user's screen.</strong>", upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='portalwidget',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
