# Generated by Django 2.1.2 on 2018-11-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='Feel free to correct the related question for any mistakes such as spelling mistakes.<br/>After submitting an answer to the question for the first time, an email will automatically be sent to the person who raised the question.', verbose_name='answer')),
                ('faq', models.BooleanField(default=False, help_text='If set True, the answer and its associated question will be appended to special FAQ section.', verbose_name='is a frequently asked question')),
                ('updated', models.DateTimeField(editable=False, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'public answer',
                'verbose_name_plural': 'public answers',
                'ordering': ['-updated', '-question__created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Required. Maximum question length of 200 characters.', max_length=200, verbose_name='question')),
                ('by_anonymous', models.BooleanField(default=False, help_text='Optional. Be anonymous to your peers when the answer to your question is posted publicly.', verbose_name='asker is anonymous to others')),
                ('created', models.DateTimeField(editable=False, verbose_name='created on')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
