# Generated by Django 2.1.2 on 2018-12-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2018-12-22 19:48:33.899589', max_length=100, verbose_name='title'),
        ),
    ]
