# Generated by Django 2.1.2 on 2018-12-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20181221_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2018-12-22 13:47:37.205580', max_length=100, verbose_name='title'),
        ),
    ]
