# Generated by Django 2.1.2 on 2018-12-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20181225_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2018-12-27 08:45:10.580492', max_length=100, verbose_name='title'),
        ),
    ]
