# Generated by Django 2.1.2 on 2018-12-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20181227_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2018-12-27 09:22:16.906680', max_length=100, verbose_name='title'),
        ),
    ]
