# Generated by Django 2.1.2 on 2018-12-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20181227_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2018-12-27 09:27:28.736138', max_length=100, verbose_name='title'),
        ),
    ]
