# Generated by Django 2.1.2 on 2018-12-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20181227_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2018-12-27 12:18:45.182608', max_length=100, verbose_name='title'),
        ),
    ]
