# Generated by Django 2.1.2 on 2018-12-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20181227_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2018-12-27 12:39:47.618555', max_length=100, verbose_name='title'),
        ),
    ]
