# Generated by Django 2.1.2 on 2018-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20181227_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2018-12-27 13:24:51.597237', max_length=100, verbose_name='title'),
        ),
    ]
