# Generated by Django 2.1.2 on 2018-12-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20181228_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2018-12-30 09:55:21.906642', max_length=100, verbose_name='title'),
        ),
    ]
