# Generated by Django 2.1.2 on 2019-01-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20181230_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2019-01-02 17:15:07.344491', max_length=100, verbose_name='title'),
        ),
    ]
