# Generated by Django 2.1.2 on 2019-01-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_auto_20190102_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2019-01-02 17:32:42.366763', max_length=100, verbose_name='title'),
        ),
    ]
