# Generated by Django 2.1.2 on 2019-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_auto_20190103_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2019-01-03 18:08:33.909275', max_length=100, verbose_name='title'),
        ),
    ]
