# Generated by Django 2.1.2 on 2019-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_auto_20190103_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2019-01-05 12:42:18.146052', max_length=100, verbose_name='title'),
        ),
    ]
