# Generated by Django 2.1.2 on 2019-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0024_auto_20190105_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2019-01-05 12:52:14.628560', max_length=100, verbose_name='title'),
        ),
    ]
