# Generated by Django 2.1.2 on 2019-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0025_auto_20190105_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2019-01-05 13:16:46.955694', max_length=100, verbose_name='title'),
        ),
    ]
