# Generated by Django 2.1.2 on 2019-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_auto_20190105_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnotification',
            name='title',
            field=models.CharField(default='Text at 2019-01-06 14:47:37.124405', max_length=100, verbose_name='title'),
        ),
    ]
